#!/usr/bin/env bash
# Function to display subdomain information
domain_info() {
    result=$(dig +short "$2"."$1")

    if [ -n "$result" ]; then
        line=$(echo "$result" | awk '{print $1}')
        echo "The subdomain $2 is a $(dig +short -t CNAME $2.$1 | awk '{print length($0) ? "CNAME" : "A"}') record and points to $line"
    else
        echo "No information found for subdomain $2."
    fi
}

# Check if correct number of arguments is provided
if [ "$#" == 1 ]; then
    # Display information for default subdomains
    domain_info "$1" "www"
    domain_info "$1" "lb-01"
    domain_info "$1" "web-01"
    domain_info "$1" "web-02"
elif [ "$#" == 2 ]; then
    # Display information for specified subdomain
    domain_info "$1" "$2"
else
    # Incorrect number of arguments
    echo "Usage: $0 Ifeoma-didi.tech [<subdomain>]"
    exit 1
fi
