#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 80
sudo ufw reload
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
