#!/usr/bin/env bash
# Installs nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 80
sudo ufw reload
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://youtube.com/@Didizworldd?si=3-DUiQasXfnnkIqK;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
